<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
	  <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.1" />
	  <PackageReference Include="StatePulse.Net.Abstractions" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dashboard\MainLayout\Pulses\States\" />
    <Folder Include="Dashboard\Pulses\" />
    <Folder Include="Event\" />
  </ItemGroup>

</Project>
